### ISSUE TITLE
Server crash upon launch

### ISSUE THREAD

**Issue by KamiSami** [Drazuam/RunicArcana#1]
Hi, uh, i stumbled on your github, hopefully looking through the bugs aswell even that i didn't find button for here in curseforge, but basically it seems this mod doesn't work on server, unsure if you are aware of this but thought to let you know anyway. Basically im getting this:

Description: Exception in server tick loop

net.minecraftforge.fml.LoadingFailedException: Loading errors encountered: [
	Runic Arcana (runicarcana) has failed to load correctly
§7Attempted to load class net/minecraftforge/client/event/GuiScreenEvent for invalid dist DEDICATED_SERVER
]
	at net.minecraftforge.fml.ModLoader.dispatchAndHandleError(ModLoader.java:201) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.ModLoader.gatherAndInitializeMods(ModLoader.java:183) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.server.ServerModLoader.begin(ServerModLoader.java:45) ~[?:?] {re:classloading}
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:122) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:613) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_221] {}

**Comment by Amperthorpe** [comment]
Hey, this mod isn't really meant to be used yet, but thanks for the heads up. We'll get this looked at.

**Comment by Drazuam** [comment]
@KamiSami , thanks for bringing this to our attention - we've got some serious issues with the dedicated server and didn't realize until just now.

**Comment by Drazuam** [comment]
Forgot to reference it, but this issue is closed by [Commit 35a9e3b](https://github.com/Drazuam/RunicArcana/commit/35a9e3b9e21221b7aab678aa54a8bc37722a589b)
